language: java
sudo: required
jdk:
  - oraclejdk8
addons:
  postgresql: '9.4'
services:
  - cassandra
before_install:
  - nvm install 0.12
  - nvm use 0.12
  - psql -c 'create database carmen;' -U postgres
  - cp src/main/resources/travis/config.properties src/main/resources/config.properties
  - cp src/main/resources/travis/logback.xml src/main/resources/logback.xml
  - cp src/main/resources/travis/hibernate.cfg.xml src/main/resources/hibernate.cfg.xml
  - git fetch --unshallow
  - rvm install ruby-2.1.5
  - rvm use 2.1.5
  - pip install --user codecov
  - bundle install
  - git clone https://github.com/Contrast-Security-OSS/cassandra-migration.git cassandra-migration && rm -rf cassandra-migration/src/test/java && cd cassandra-migration && mvn clean install && cd ..
  - mvn compile
  - gem install sass
install:
  - mvn flyway:migrate
  - mvn exec:java -Dexec.mainClass="com.cezarykluczynski.carmen.db.CassandraMigrations"
  - sudo service cassandra restart
  - npm install --global grunt-cli typings tsd
  - cd src/main/webapp/frontend && npm install && cd ../../../..
  - mvn test -Dtest="BeforeAll"
script:
  - cd src/main/webapp/frontend && grunt to && cd ../../../..
  - mvn verify
  - rspec
env:
  global:
    - secure: J4OhtLGCbT3N/ZzJ86NxN45dYw6HvJ96csigQTX3HkdjLXHs+xptu1t964SXrxbttRKl6dehGBZrCix8wscJLGIe0+BPhzdMZjifhcbmEbs1s9ieABSEuxeAX64aSqtLH5ULXC544V7sVsihONyO2ftuE76msOLmP7/Wh0yXu9kfrwCe2Cnihiczrq/qHNH8fhV4ft0/rMwBRF7rd01oumJGn4gbJngP4IUqM/fbBfX7Z8rlS9fbvIl6gsul1sWpnM9mWSUyTYqb+JdjX8b+xcSBc0Huvn+ebC36uzGZuHpya+DdA8qWIUyb9f/+V0FljLNSqlZlP7DJMaE5I9r9bdDeQ8YWNXwj2Vc6sGpBKzo+3D0x+pZ5ieeZV2GOIY19ZCuq7/FAsNxwDISsAnTylrwEJVxkSw7NtaQzC4XpYn/L2mktRBNdYN2au0uK/fR3R2UsX64n5GUED/yTYHKD5XZdGZ+tLMNSvT7YYcHPtoWAd8y593vojui3KRa6pDY/JGSfXBSTO9LEYSlGiNQWFwA1+qcUXvoYKgFIW5Ee21/ehX389HzBCMAlz9mxIsgmmFcK/jxxdA7Q7wzzvaOsks+TehNg9BSpOx8gIPxJmfXd15/dsuvTPodGT5I0sW0MGczGZhbhnLoOCR+un14xSv+nixixYDuXKuUaXcvJNKk=
    - secure: Q6bkw3nx+DaJo1yeuxYHJTnt6feoEBlh5heuwnnenJ0OOZXO0uKjke29+N70Yrhx7DwY2vlWWakedoBRsAKm8I67ixHg/aDjmc03wR1w+bu8yyTakSQ310PBVC1E2IZj1Cy0kUQKiwpT0rp2uJ9F7UR781EzvP9h3M4APq9i3hCH2BfA0c9eawnqxlfS26N+2jqo9Z5okN0j10+LXcSMLDMbtmbSdzc1Ehxfnu+aBCF5bcRR0/K3FkClE1Uwi+lF/JpWnvbjwGjdsoZGshxuDKBEnv0neQg2Qm7PSRrKq1KoSxHis3+ehkMTq0ENPBJxsuQDOqmgnOP0ia/kXuaSFqz8EZqYWWIuyUChfdFigIAMgqdbfOKfVlD0A6X3Vbu6mCnqOo/TkpPp9nk0Yrr/PYSRl/naoU72JaX3Irb+y3oezJj1A9Fve1YJDUqPmktnKLVZ2eUY/QzBeKYUCPnj+6pmL6Vo00rGMVJGBj3shZMbX7rOTME7H1jfBPe6u8Oip1jwHFG6kRKvO5WQ8Oh2Kc5xVZ+Ko6TeYQtUn0NoQs+SBo7fBqHO7TrobbvCUA83RPOiWhVhWLyyBqci6HLM9bRZgxGZE2bnJpYjZ/6xbJkjB4sS26ELtSbCcT3pyIbrPhs437fjq//MXOcDyYkcVNUOmXzatQ+RQSjPxnSNzyk=
