sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: '9.4'
services:
  - cassandra
before_install:
  - echo | sudo add-apt-repository ppa:git-core/ppa
  - sudo apt-get update
  - sudo apt-get --assume-yes install git=1:2.6.4-0ppa1~ubuntu14.04.1
  - git --version
  - echo "deb http://www.apache.org/dist/cassandra/debian 22x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - gpg --keyserver pgp.mit.edu --recv-keys F758CE318D77295D && gpg --export --armor F758CE318D77295D | sudo apt-key add -
  - gpg --keyserver pgp.mit.edu --recv-keys 2B5C1B00 && gpg --export --armor 2B5C1B00 | sudo apt-key add -
  - gpg --keyserver pgp.mit.edu --recv-keys 0353B12C && gpg --export --armor 0353B12C | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get --assume-yes install cassandra
  - sudo service cassandra status
  - nodetool enablethrift
  - nvm install 0.12
  - nvm use 0.12
  - psql -c 'create database carmen;' -U postgres
  - cp src/main/resources/travis/config.properties src/main/resources/config.properties
  - mvn compile
install:
  - mvn flyway:migrate
  - mvn exec:java -Dexec.mainClass="com.cezarykluczynski.carmen.db.CassandraMigrations"
  - npm install --global gulp
  - npm install
  - gulp
script:
  - mvn cobertura:cobertura-integration-test -Dcobertura.report.format=xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: J4OhtLGCbT3N/ZzJ86NxN45dYw6HvJ96csigQTX3HkdjLXHs+xptu1t964SXrxbttRKl6dehGBZrCix8wscJLGIe0+BPhzdMZjifhcbmEbs1s9ieABSEuxeAX64aSqtLH5ULXC544V7sVsihONyO2ftuE76msOLmP7/Wh0yXu9kfrwCe2Cnihiczrq/qHNH8fhV4ft0/rMwBRF7rd01oumJGn4gbJngP4IUqM/fbBfX7Z8rlS9fbvIl6gsul1sWpnM9mWSUyTYqb+JdjX8b+xcSBc0Huvn+ebC36uzGZuHpya+DdA8qWIUyb9f/+V0FljLNSqlZlP7DJMaE5I9r9bdDeQ8YWNXwj2Vc6sGpBKzo+3D0x+pZ5ieeZV2GOIY19ZCuq7/FAsNxwDISsAnTylrwEJVxkSw7NtaQzC4XpYn/L2mktRBNdYN2au0uK/fR3R2UsX64n5GUED/yTYHKD5XZdGZ+tLMNSvT7YYcHPtoWAd8y593vojui3KRa6pDY/JGSfXBSTO9LEYSlGiNQWFwA1+qcUXvoYKgFIW5Ee21/ehX389HzBCMAlz9mxIsgmmFcK/jxxdA7Q7wzzvaOsks+TehNg9BSpOx8gIPxJmfXd15/dsuvTPodGT5I0sW0MGczGZhbhnLoOCR+un14xSv+nixixYDuXKuUaXcvJNKk=
