language: java
jdk:
  - oraclejdk8
addons:
  postgresql: '9.4'
before_install:
  - psql -c 'create database carmen;' -U postgres
  - mvn compile
  - mvn flyway:migrate
  - nvm install 0.12
  - nvm use 0.12
  - npm install --global gulp
  - npm install
  - gulp
install:
  script:
  - mvn test
