language: java
jdk:
  - oraclejdk8
addons:
  postgresql: '9.4'
before_install:
  - nvm install 0.12
  - nvm use 0.12
  - psql -c 'create database carmen;' -U postgres
  - mvn compile
install:
  - mvn flyway:migrate
  - npm install --global gulp
  - npm install
  - gulp
script:
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
